+incdir+../../rtl+./src+../../deps/svlogger/
../../rtl/axicb_crossbar_top.sv
../../rtl/axicb_mst_if.sv
../../rtl/axicb_mst_switch.sv
../../rtl/axicb_mst_switch_wr.sv
../../rtl/axicb_mst_switch_rd.sv
../../rtl/axicb_round_robin.sv
../../rtl/axicb_round_robin_core.sv
../../rtl/axicb_scfifo.sv
../../rtl/axicb_scfifo_ram.sv
../../rtl/axicb_scfifo_regfile.sv
../../rtl/axicb_slv_if.sv
../../rtl/axicb_slv_switch.sv
../../rtl/axicb_slv_ooo.sv
../../rtl/axicb_slv_switch_wr.sv
../../rtl/axicb_slv_switch_rd.sv
../../rtl/axicb_switch_top.sv
../../rtl/axicb_pipeline.sv
./src/mst_driver.sv
./src/slv_monitor.sv
./src/lfsr.sv
./src/pipeline_checker.sv
../../deps/dcfifo/src/vlog/async_bidir_fifo.v
../../deps/dcfifo/src/vlog/async_bidir_ramif_fifo.v
../../deps/dcfifo/src/vlog/async_fifo.v
../../deps/dcfifo/src/vlog/fifo_2mem.v
../../deps/dcfifo/src/vlog/fifomem_dp.v
../../deps/dcfifo/src/vlog/rptr_empty.v
../../deps/dcfifo/src/vlog/sync_ptr.v
../../deps/dcfifo/src/vlog/sync_r2w.v
../../deps/dcfifo/src/vlog/sync_w2r.v
../../deps/dcfifo/src/vlog/wptr_full.v
