name: AXI-CROSSBAR
on: [push]
jobs:
  Lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: ./flow.sh lint
  Synthesis:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: ./flow.sh syn
  Simulation-AXI4:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: ./flow.sh sim axi4
  Simulation-AXI4-lite:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: ./flow.sh sim axi4lite
